# Generated by Django 2.1 on 2022-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220108_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.CharField(default=91, max_length=10),
        ),
    ]
