# Generated by Django 2.1 on 2022-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220108_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
