# Generated by Django 2.1 on 2022-01-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220108_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('no_of_surveys', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='cardtype',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='no_of_surveys',
            new_name='off_id',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='place',
            new_name='rationcard',
        ),
    ]
