# Generated by Django 2.1 on 2022-01-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_survey_cardtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benifits',
            new_name='Benifit',
        ),
    ]
