# Generated by Django 2.1 on 2022-01-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_benifits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benifits',
        ),
    ]
