# Generated by Django 2.1 on 2022-01-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_benifits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benifit',
            new_name='Benifits',
        ),
    ]
