# Generated by Django 4.0.1 on 2022-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220115_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='district',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
