# Generated by Django 4.0.1 on 2022-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_people_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='district',
            new_name='District',
        ),
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='salary',
            field=models.CharField(max_length=10),
        ),
    ]
