# Generated by Django 2.1 on 2021-12-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),

            ],
        ),
    ]
