# Generated by Django 2.1 on 2022-01-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
