# Generated by Django 2.1 on 2022-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220108_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='designation',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='people',
            name='Aadhar_no',
            field=models.CharField(max_length=12),
        ),
    ]
