# Generated by Django 2.1 on 2022-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220108_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benifits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.IntegerField()),
                ('rationcard', models.CharField(max_length=8)),
                ('dall', models.IntegerField()),
                ('sugar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('no_of_surveys', models.IntegerField()),
            ],
        ),
    ]
