# Generated by Django 2.1 on 2022-01-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_benifits_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ssn',
        ),
    ]
