# Generated by Django 2.1 on 2022-01-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220108_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='cardtype',
        ),
    ]
