# Generated by Django 2.1 on 2022-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220115_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benifits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationcard', models.CharField(max_length=8)),
                ('rice', models.IntegerField()),
                ('dall', models.IntegerField()),
                ('sugar', models.IntegerField()),
            ],
        ),
    ]
