# Generated by Django 4.0.1 on 2022-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_district_people_district_alter_people_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='RD_NO',
            field=models.CharField(default='RD', max_length=15),
        ),
    ]
