# Generated by Django 2.2.26 on 2022-02-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_people_rd_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='statement',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
