# Generated by Django 2.2.26 on 2022-02-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_people_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benifits',
        ),
        migrations.DeleteModel(
            name='survey',
        ),
    ]
